### ISSUE TITLE
Quando a pessoa não tem foto, aparece a imagem de um link quebrado.

### ISSUE THREAD

**Issue by llagerlof** [shermangray/agenda#4]
Seria visualmente melhor se a imagem de link quebrado não aparecesse caso a pessoa cadastrada não tivesse foto, tanto na listagem como no formulário de alteração.

**Comment by llagerlof** [comment]
A atualização resolveu a questão do link quebrado na listagem, mas não na tela que exibe o conta individualmente (a tela de alteração de contato).

Obrigado pela correção!

**Comment by shermangray** [comment]
Caro Amigo, já farei esse acerto. Obrigado!!!

**Comment by shermangray** [comment]
Lawrence, fiz o acerto no local apontado por você, e implementei o script editar.php, passando para o tpl, apenas o array e não todos os índices separados. Obg pela colaboração, Abs!!!
